language: node_js
node_js: 10
services:
  - docker
before_script:
  - yarn
script:
  - yarn start:graphnode &
  - sleep 20 #making sure the graph is up and running
  - yarn test
  - yarn lint
  - yarn build:release && yarn package:release
after_success:
  - codecov
