language: node_js
node_js: 10
services:
  - docker
before_script:
  - yarn
script:
  - docker-compose -f ./node_modules/@daostack/client/docker-compose.yml up -d graph-node
  - sleep 20 #making sure the graph is up and running
  - ./script/wait-for-subgraph.sh
  - yarn test
  - yarn lint
  - yarn build:release && yarn package:release
after_success:
  - codecov
